"""Constants for tests."""

from homeassistant.const import (
    CONF_LATITUDE,
    CONF_LONGITUDE,
    CONF_MODE,
    CONF_MONITORED_CONDITIONS,
    CONF_NAME,
    CONF_SENSORS,
)

from custom_components.gismeteo.const import (
    CONF_PLATFORM_FORMAT,
    CONF_WEATHER,
    FORECAST_MODE_HOURLY,
    SENSOR,
    WEATHER,
)

FAKE_NAME = "Home"
FAKE_UNIQUE_ID = "test_id"
FAKE_LATITUDE = 55.55
FAKE_LONGITUDE = 122.12

FAKE_CONFIG = {
    CONF_NAME: FAKE_NAME,
    CONF_LATITUDE: FAKE_LATITUDE,
    CONF_LONGITUDE: FAKE_LONGITUDE,
}

FAKE_CONFIG_OPTIONS = {
    CONF_PLATFORM_FORMAT.format(WEATHER): True,
    CONF_PLATFORM_FORMAT.format(SENSOR): True,
}

FAKE_CONFIG_YAML = {
    "home": {
        CONF_NAME: FAKE_NAME,
        CONF_LATITUDE: FAKE_LATITUDE,
        CONF_LONGITUDE: FAKE_LONGITUDE,
        CONF_WEATHER: {CONF_MODE: FORECAST_MODE_HOURLY},
        CONF_SENSORS: {CONF_MONITORED_CONDITIONS: ["condition"]},
    },
}
