default_config:

logger:
  default: error
  logs:
    custom_components.gismeteo: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

#sensor:
#  - platform: gismeteo
#    monitored_conditions:
#      - temperature
#      - temperature_feeling
#
#weather:
#  - platform: gismeteo
