default_config:

logger:
  default: error
  logs:
    custom_components.gismeteo: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

gismeteo:
  sweet_home:
    weather: {}
    sensors:
      monitored_conditions:
        - temperature
        - humidity

  dacha:
    name: Our Country House
    latitude: 46.0561601
    longitude: 13.1741225
    sensors:
      monitored_conditions:
        - temperature
        - humidity
      forecast_days: 2
