default_config:

logger:
  default: error
  logs:
    custom_components.gismeteo: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

#sensor:
#  - platform: gismeteo
#    name: Sweet Home
#    monitored_conditions:
#      - temperature
#      - humidity
#
#weather:
#  - platform: gismeteo
#    name: Sweet Home
#    latitude: ...
#    longitude: ...
#    mode: hourly  # Default value

gismeteo:
  sweet_home:
    weather: {}
    sensors:
      monitored_conditions:
        - temperature
        - humidity

  dacha:
    name: Our Country House
#    latitude: ...
#    longitude: ...
    sensors:
      monitored_conditions:
        - temperature
        - humidity
      forecast_days: 2
